services:
  web:
    image: render/python3.8-slim
    command: gunicorn -b 0.0.0.0:8000 djangoChatApp.wsgi:application
    environment:
      DJANGO_SETTINGS_MODULE: djangoChatApp.settings.py
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '9886550'
