services:
  web:
    image: render/python3.11.4-slim
    command: gunicorn -b 0.0.0.0:8000 chatappprj.wsgi:application
    environment:
      DJANGO_SETTINGS_MODULE: chatappprj.settings.py
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: '9886550'
